"""Add gt_sentiment, comments, and is_mock columns to entity_sentiments

Revision ID: 1a64f32a24a2
Revises: fd996ec0aab4
Create Date: 2025-03-29 22:00:41.044528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a64f32a24a2'
down_revision: Union[str, None] = 'fd996ec0aab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_sentiments', sa.Column('gt_sentiment', sa.String(length=10), nullable=True))
    op.add_column('entity_sentiments', sa.Column('is_mock', sa.Boolean(), nullable=True, server_default=sa.text('0')))
    op.add_column('entity_sentiments', sa.Column('comments', sa.Text(), nullable=True))
    op.create_index(op.f('ix_entity_sentiments_gt_sentiment'), 'entity_sentiments', ['gt_sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_sentiments_gt_sentiment'), table_name='entity_sentiments')
    op.drop_column('entity_sentiments', 'comments')
    op.drop_column('entity_sentiments', 'is_mock')
    op.drop_column('entity_sentiments', 'gt_sentiment')
    # ### end Alembic commands ###
